
export const ADDCART_REQUEST = "ADDCART_REQUEST";
export const ADDCART_SUCCESS = "ADDCART_SUCCESS";
export const ADDCART_FAILURE = "ADDCART_FAILURE";

export const INCREMENTCART_REQUEST = "INCREMENTCART_REQUEST";
export const INCREMENTCART_SUCCESS = "INCREMENTCART_SUCCESS";
export const INCREMENTCART_FAILURE = "INCREMENTCART_FAILURE";

export const DECREMENT_REQUEST = "DECREMENT_REQUEST";
export const DECREMENT_SUCCESS = "DECREMENT_SUCCESS";
export const DECREMENT_FAILURE = "DECREMENT_FAILURE";

export const GETCART_REQUEST = "GETCART_REQUEST";
export const GETCART_SUCCESS = "GETCART_SUCCESS";
export const GETCART_FAILURE = "GETCART_FAILURE";

export const CLEAR_CART = "CLEAR_CART";

export const CHECKING_CART = "CHECKING_CART";
export const NOT_CHECKING_CART = "NOT_CHECKING_CART";


