export const CURRENT_RES_REQUEST = "CURRENT_RES_REQUEST";
export const CURRENT_RES_SUCCESS = "CURRENT_RES_SUCCESS";
export const CURRENT_RES_FAILURE = "CURRENT_RES_FAILURE";

export const RES_MENU_REQUEST = "RES_MENU_REQUEST";
export const RES_MENU_SUCCESS = "RES_MENU_SUCCESS";
export const RES_MENU_FAILURE = "RES_MENU_FAILURE";