export const SET_CITY = "SET_CITY";
export const SET_DISH = "SET_DISH";
export const SET_CITY_ID = "SET_CITY_ID";


export const SET_FILTER = "SET_FILTER";


export const SET_CITY_POSITION = "SET_CITY_POSITION";

export const SET_LOC_FILTER = "SET_LOC_FILTER";



export const RES_REQUEST = "RES_REQUEST";
export const RES_SUCCESS = "RES_SUCCESS";
export const RES_FAILURE = "RES_FAILURE";

export const CLICKED_RES_REQUEST = "CLICKED_RES_REQUEST";
export const CLICKED_RES_SUCCESS = "CLICKED_RES_SUCCESS";
export const CLICKED_RES_FAILURE = "CLICKED_RES_FAILURE";


export const RES_MENU_REQUEST = "RES_MENU_REQUEST";
export const RES_MENU_SUCCESS = "RES_MENU_SUCCESS";
export const RES_MENU_FAILURE = "RES_MENU_FAILURE";